version: 2
updates:
  - package-ecosystem: npm
    directory: /backend/db_config
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
